services:
  festival-app:
    container_name: festival-app
    image: festival-app:latest
    build: .
    depends_on:
      - postgres-db
    ports:
      - '9090:9090'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - festival-network

  postgres-db:
    image: postgres:9.6
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./data:/Users/sijmen/Java/festival_app/data
    networks:
      - festival-network
    hostname: postgres
    env_file:
      - .env

  mongodb:
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=mongodb
    ports:
      - '27017:27017'
    image: mongo
    networks:
      - festival-network
    hostname: mongo
    depends_on:
      - festival-app

  review-app:
    container_name: review-app
    image: review-app:latest
    build: ../review_app/
    depends_on:
      - mongodb
    ports:
      - '9091:9091'
    networks:
      - festival-network
    environment:
      - DATABASE_HOST=host.docker.internal
      - SPRING.DATA.MONGODB.URI=mongodb://mongodb:27017

networks:
  festival-network:
    driver: bridge